### ISSUE TITLE
Docs: does it exist a roadmap? What about Stylelint?

### ISSUE THREAD

**Issue by ghost** [eslint/css#34]
Please inform:

- the scope of @eslint/css that you want to achieve;
- what makes you think that you are prioritizing correctly when building rules for @eslint/css?
- can you provide a roadmap for @eslint/css?
- do you think that @eslint/css is going to replace Stylelint or just to complement it as a background linter?

**Comment by nzakas** [comment]
Thanks for the questions. At this point, we don't really have answers for all of them.

Why? When we asked people what languages they wanted to use ESLint to lint, CSS was one of the top four answers (along with JSON, Markdown, and YAML). 

Roadmap? Not yet. We are really looking for feedback on what people want or would find useful.

A few things about Stylelint:

1. One member of the Stylelint team has been actively engaging with this project already. I'm hopeful more will join.
2. Our intent is not to duplicate every rule that Stylelint has, partly because we don't always agree on the rule granularity, partly because some of the rules are outdated, and partly because we just think there are more important things to focus on. So, our goal is not to produce something that people can just swap in for Stylelint later.
3. One thing we heard from folks is that writing custom rules in Stylelint is difficult, and we feel that ESLint's API makes this relatively easy. 
4. In talking with people, there seem to be a lot who use Stylelint because there aren't any other options for CSS but aren't particularly happy with the user experience.

Ultimately, we'd like this plugin to end being guided by folks who are passionate about CSS. The end game is definitely not for me to implement or suggest every rule or addition. I'm just working on getting a solid foundation set so it's easy for others to build upon.

**Comment by romainmenke** [comment]
> One thing we heard from folks is that writing custom rules in Stylelint is difficult, and we feel that ESLint's API makes this relatively easy.

> In talking with people, there seem to be a lot who use Stylelint because there aren't any other options for CSS but aren't particularly happy with the user experience.

Are there any details you can share about this?

If there are things that can be improved in Stylelint, either it's API or docs it would be nice to hear this feedback :)

I do agree that having a single tool for linting any language and only needing to learn a single API is better than having slightly different tools for each language.
But maybe there are some quick wins for users of Stylelint?
